project_id = "pjnbsuwkxzxcfaetywjs"

[functions.generate-recurring-receivables]
verify_jwt = false

[functions.generate-recurring-payables]
verify_jwt = false

[functions.check-expiring-items]
verify_jwt = false

[functions.create-client-user]
verify_jwt = true

[functions.create-contact-user]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.manage-asaas-secret]
verify_jwt = true

[functions.test-asaas-connection]
verify_jwt = true

[functions.create-asaas-customer]
verify_jwt = true

[functions.create-asaas-payment]
verify_jwt = true

[functions.sync-asaas-payment]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false