project_id = "pjnbsuwkxzxcfaetywjs"

[functions.generate-recurring-receivables]
verify_jwt = false

[functions.generate-recurring-payables]
verify_jwt = false

[functions.check-expiring-items]
verify_jwt = false

[functions.create-client-user]
verify_jwt = true
