project_id = "pjnbsuwkxzxcfaetywjs"

[functions.generate-recurring-receivables]
verify_jwt = false

[functions.generate-recurring-payables]
verify_jwt = false

[functions.check-expiring-items]
verify_jwt = false

[functions.create-client-user]
verify_jwt = true

[functions.create-contact-user]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.test-asaas-connection]
verify_jwt = true

[functions.create-asaas-customer]
verify_jwt = true

[functions.create-asaas-payment]
verify_jwt = true

[functions.sync-asaas-payment]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = true

[functions.sync-google-calendar]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true

[functions.send-maintenance-whatsapp]
verify_jwt = true

[functions.check-pending-maintenances]
verify_jwt = false

[functions.google-calendar-oauth]
verify_jwt = false